local:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

amazon:
  service: S3
  bucket: ENV['S3_TILESETS_BUCKET']
  access_key_id: ENV['S3_TILESETS_KEY_ID']
  secret_access_key: ENV['S3_TILESETS_KEY_SECRET']
